<div class="container">

<table style="width: 100%;"><tr>
<td>DebugPrintFn</td>
<td style="text-align: right;">R Documentation</td>
</tr></table>
<h2>Capture arguments of exception throwing function call for later debugging.</h2>

<h3>Description</h3>

<p>Run fn and print result, save arguments on failure.  Use on systems like <code>ggplot()</code>
where some calculation is delayed until <code>print()</code>.
Please see: <code>vignette("DebugFnW", package="wrapr")</code>.
</p>


<h3>Usage</h3>

<pre><code class="language-R">DebugPrintFn(saveDest, fn, ...)
</code></pre>


<h3>Arguments</h3>

<table>
<tr style="vertical-align: top;">
<td><code>saveDest</code></td>
<td>
<p>where to write captured state (determined by type): NULL random temp file, character temp file, name globalenv() variable, and function triggers callback.</p>
</td>
</tr>
<tr style="vertical-align: top;">
<td><code>fn</code></td>
<td>
<p>function to call</p>
</td>
</tr>
<tr style="vertical-align: top;">
<td><code>...</code></td>
<td>
<p>arguments for fn</p>
</td>
</tr>
</table>
<h3>Value</h3>

<p>fn(...) normally, but if fn(...) throws an exception save to saveDest RDS of list r such that do.call(r$fn,r$args) repeats the call to fn with args.
</p>


<h3>See Also</h3>

<p><code>dump.frames</code>, <code>DebugFn</code>, <code>DebugFnW</code>,  <code>DebugFnWE</code>, <code>DebugPrintFn</code>, <code>DebugFnE</code>, <code>DebugPrintFnE</code>
</p>


<h3>Examples</h3>

<pre><code class="language-R">
saveDest &lt;- paste0(tempfile('debug'),'.RDS')
f &lt;- function(i) { (1:10)[[i]] }
# correct run
DebugPrintFn(saveDest, f, 5)
# now re-run
# capture error on incorrect run
tryCatch(
   DebugPrintFn(saveDest, f, 12),
   error = function(e) { print(e) })
# examine details
situation &lt;- readRDS(saveDest)
str(situation)
# fix and re-run
situation$args[[1]] &lt;- 6
do.call(situation$fn,situation$args)
# clean up
file.remove(saveDest)

</code></pre>


</div>